; PlatformIO Project Configuration File — Radar de vuelos
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev

; ------------- entorno para la placa -------------
[env:esp32dev]
platform      = espressif32@^6.5.0
board         = esp32dev
framework     = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
  bblanchon/ArduinoJson@^7.0.4
  esphome/ESPAsyncWebServer-esphome@^3.2.2
  esphome/AsyncTCP-esphome@^2.1.4
build_flags =
  -DCORE_DEBUG_LEVEL=3           ; INFO
  -std=gnu++17
build_unflags =
  -std=gnu++11

; ------------- entorno para tests en desktop -------------
[env:native]
platform  = native
test_framework = unity
build_flags =
  -std=gnu++17
  -DUNIT_TEST
  -I src
lib_deps =
  fabiobatsilva/ArduinoFake@^0.4.0
  bblanchon/ArduinoJson@^7.0.4
test_ignore =
